import './globals.css';
import type { Metadata } from 'next';
import { Roboto } from 'next/font/google';
import ThemeRegistry from './components/ThemeRegistry/ThemeRegistry';
import { Navbar } from './components/Navbar';

export const metadata: Metadata = {
  title: 'Sistema de rastreamento de veículos',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ThemeRegistry>
          <Navbar />
          {children}
        </ThemeRegistry>
      </body>
    </html>
  );
}
